name: linting

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  run-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Run linting
        run: yarn run lint
